config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "pictures#index"
  resources :pictures do
    resources :comments
    resources :likes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_attached_file :image, :styles => { :medium => "600x600>", :thumb => "300x300>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def new
    @picture = Picture.find(params[:picture_id])
    @comment = Comment.new
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @picture.comments.create(comment_params)
    redirect_to pictures_path
  end

  def comment_params
    params.require(:comment).permit(:thoughts)
  end

  def edit
    # @picture = Picture.find(params[:picture_id])
    @comment= Comment.find(params[:id])
  end

  def destroy
    # @picture = Picture.find(params[:picture_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to '/pictures'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to pictures_path
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @picture.likes.create
    redirect_to pictures_path
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  def index
    @pictures = Picture.all
    # render('layouts/application')
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.create(picture_params)
    redirect_to '/pictures'
  end

  def picture_params
    params.require(:picture).permit(:name, :image)
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    @picture.update(picture_params)
    redirect_to '/pictures'
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:notice] = 'Picture deleted successfully'
    redirect_to '/pictures'
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController 
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/edit.html.erb
<%= form_for [@picture, @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_field :thoughts %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/comments/new.html.erb
<%= form_for [@picture, @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_field :thoughts %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<center><B>Guillaume's awful version of </B><img src='https://ambiently.files.wordpress.com/2013/05/instagram-logo-small1.jpg?w=604'></center><br><br>
<%= yield %>

<BR><BR><%= link_to "Back to Homepage", pictures_path %>
</body>
<footer>
<br><br>
<% if user_signed_in? %>
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>
</footer>
</html>

app/views/pictures/edit.html.erb
<%= form_for @picture, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/pictures/index.html.erb
<% if @pictures.any? %>
  <% @pictures.each do |picture| %>
    <h2><%= link_to picture.name, picture_path(picture) %></h2>
    <%= image_tag picture.image.url(:medium) %><br>
    
    <%= link_to "Edit #{picture.name}", edit_picture_path(picture) %>
    <%= link_to "Delete #{picture.name}", picture_path(picture), method: :delete %>
    <%= link_to 'Add a comment', new_picture_comment_path(picture)%>
    <%= link_to 'like this', picture_likes_path(picture), method: :post %>
    <%= pluralize(picture.likes.count, "like") %>

    <h3>Comments for <%= picture.name %></h3>
    <% if picture.comments.any? %>
      <% picture.comments.each do |comment| %>
        <h3><%= comment.thoughts %></h3>
      <br>
<!--       These 2 are failing and I dont know why! Spike? Dan? Help! -->
      <%= link_to "Edit Comment", edit_picture_comment(@picture, @comment) %>
      <%= link_to "Delete Comment", picture_comments_path(@picture, @comment), method: :delete %>
      <% end %>
    <% end %>
<!--     Ask Spike. I want to leave a comment on a picture without any page redirection / Tried for 2 hours. Didnt work -->
    <% end %>
  <% else %>
  No pictures yet!<br><br>
<% end %>

<%= notice %>
<%= yield %><br><br>
<a href='/pictures/new'>Add a picture</a>

app/views/pictures/new.html.erb
<%= form_for @picture, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/pictures/show.html.erb
<p><%= @picture.name %></p>